name: 🚀 Deploy website on push
on: push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files to admin
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ftp.capitalradio.co.ug
        port: 22
        username: capitalradio
        password: '-X2i3g6+Agj_'
        local_path: './admin_frontend/dist/*'
        remote_path: '/home/capitalradio/admin/'
        sftp_only: true
