name: 🚀 Deploy website on push
on: push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files to admin
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.capitalradio.co.ug
        port: 22
        username: "capitalradio"
        password: '-X2i3g6+Agj_'
        server-dir: /home/capitalradio/admin/
        local-dir: admin_frontend/dist/
        exclude: |
          **/__pycache__/**
          **/*.pyc
          **/*.pyo
          **/.git/**
          **/.gitignore
          **/venv/**
          **/.env
          **/logs/**
          **/*.log
